### ISSUE TITLE
Won't install MacOS 10.14.1

### ISSUE THREAD

**Issue by randycasburn** [confirmedcode/Confirmed-Mac#1]
With validated account:

1. Launch installer
2. Log in
3. Accept terms
4. Click install

Result - App disappears, app does not install, app is not running in background, worst of all - no indication of error, result, no feedback at all.

**Comment by jar-son** [comment]
Noticed this log

> Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=260 "The file “severCertProtected.p12” couldn’t be opened because there is no such file." UserInfo={NSFilePath=~/Library/Application Support/com.confirmed.tunnelsMac/severCertProtected.p12, NSUnderlyingError=0x7fa8cdd003b0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}: file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang_Fall2018/swiftlang_Fall2018-1000.11.42/src/swift/stdlib/public/core/ErrorType.swift, line 184
> [1]    97734 illegal hardware instruction  ./Confirmed\ VPN

**Comment by hijohnnylin** [comment]
Hello, thanks for reporting this!

We've been able to reproduce the issue and are testing a fix now -- update should arrive within an hour or two. Sorry for the inconvenience.

Cheers,
Johnny

**Comment by randycasburn** [comment]
Yes. installed correctly now. Thanks for the quick work! I'm going to file another issue to address a UI issue, but this one can close.

**Comment by rahulda1** [comment]
Fixed in https://github.com/confirmedcode/Confirmed-Mac/commit/8404240465172113ff82b686fb53da4c420f552c
