### ISSUE TITLE
Mac OS 10.14.1 Dark Mode font color unreadable

### ISSUE THREAD

**Issue by randycasburn** [confirmedcode/Confirmed-Mac#2]
![screen shot 2018-12-12 at 2 19 22 pm](https://user-images.githubusercontent.com/1176839/49896666-af17a500-fe19-11e8-827f-933087dc054c.jpg)

Both settings views are unreadable in dark mode.

**Comment by hijohnnylin** [comment]
On it. Thanks for reporting this!

**Comment by rahulda1** [comment]
Fixed in https://github.com/confirmedcode/Confirmed-Mac/commit/b907a38bd3e451b64bd5eafcce7b75f4daec6fe5
