### ISSUE TITLE
Crashes, uses between 300 - 600% CPU when waking from sleep

### ISSUE THREAD

**Issue by Tam** [confirmedcode/Confirmed-Mac#4]
The app crashes, using between 300%  to 600% CPU when waking from sleep. The issue is persistent across both my late 2015 iMac and 2016 MacBook Pro.

**Comment by rahulda1** [comment]
Hey Tam,

I think we fixed this issue - what version of Confirmed are you on?

**Comment by Tam** [comment]
I'm on version 0.3.9-v3.

I have a feeling it might be something to do with Little Snitch's network filter blocking, so I've allowed all requests for the Confirmed app to see if it helps.

**Comment by rahulda1** [comment]
We have 0.4.1 which should fix it. Can you try it from our website (haven't rolled it out through the updater because we are still validating).

**Comment by Tam** [comment]
I'm not sure if it was the update or allowing all app requests through Little Snitch, but the issue seems to have been resolved. Thanks for your help!
